/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Audio, Image } from "@boundaryml/baml"
import type { Check, Checked } from "./types";
import type { Citation, MedicalInsight, Resume } from "./types";
import type * as types from "./types";

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
	value: T;
	state: "Pending" | "Incomplete" | "Complete";
}

export namespace partial_types {
	export interface Citation {
		title?: string | null;
		authors?: (string | null)[];
		journal?: string | null;
		year?: number | null;
		pmid: (string | null) | null;
		doi: (string | null) | null;
		relevance_score?: number | null;
	}

	export interface MedicalInsight {
		summary?: string | null;
		key_findings?: (string | null)[];
		citations?: (partial_types.Citation | null)[];
		recommendations?: (string | null)[];
		confidence_level?: string | null;
	}

	export interface Resume {
		name?: string | null;
		email?: string | null;
		experience?: (string | null)[];
		skills?: (string | null)[];
	}
}
