/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, Image } from "@boundaryml/baml"
import type { Check, Checked } from "./types";
import type {
	ChatResponseWithTools,
	Citation,
	E2BCodeRequest,
	MedicalChatResponse,
	MedicalContext,
	MedicalInsight,
	PAAppealStrategy,
	PADrugInfo,
	PAExtractionResult,
	PAJustificationResult,
	PAPatientData,
	PAPayerRequirements,
	Resume,
	Tool,
	ToolCall,
	ToolType,
} from "./types";
import type * as types from "./types";

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
	value: T;
	state: "Pending" | "Incomplete" | "Complete";
}

export namespace partial_types {
	export interface ChatResponseWithTools {
		message?: string | null;
		requires_tools?: boolean | null;
		tool_calls: ToolCall[];
		citations: Citation[];
	}
	export interface Citation {
		title?: string | null;
		authors: string[];
		journal?: string | null;
		year?: number | null;
		pmid?: string | null;
		doi?: string | null;
		relevance_score?: number | null;
	}
	export interface E2BCodeRequest {
		code?: string | null;
		description?: string | null;
		packages: string[];
		expected_output?: string | null;
	}
	export interface MedicalChatResponse {
		message?: string | null;
		requires_tools?: boolean | null;
		tool_calls: ToolCall[];
		medical_context?: MedicalContext | null;
		suggestions: string[];
	}
	export interface MedicalContext {
		condition?: string | null;
		severity?: string | null;
		treatment_options: string[];
		key_considerations: string[];
		requires_literature?: boolean | null;
	}
	export interface MedicalInsight {
		summary?: string | null;
		key_findings: string[];
		citations: Citation[];
		recommendations: string[];
		confidence_level?: string | null;
	}
	export interface PAAppealStrategy {
		denial_root_cause?: string | null;
		documentation_gaps: string[];
		additional_evidence_needed: string[];
		appeal_strategy?: string | null;
		recommend_peer_to_peer?: boolean | null;
		peer_to_peer_talking_points?: string[] | null;
		timeline_recommendation?: string | null;
		success_likelihood?: string | null;
	}
	export interface PADrugInfo {
		drug_name?: string | null;
		generic_name?: string | null;
		indication?: string | null;
		mechanism?: string | null;
	}
	export interface PAExtractionResult {
		genotype?: string | null;
		voe_count_past_year?: number | null;
		hospitalization_count?: number | null;
		current_therapies: string[];
		failed_therapies: string[];
		hemoglobin?: number | null;
		hemoglobin_f_percentage?: number | null;
		extraction_notes: string[];
	}
	export interface PAJustificationResult {
		justification?: string | null;
		citations: Citation[];
		confidence_level?: string | null;
		key_points: string[];
		warnings: string[];
	}
	export interface PAPatientData {
		genotype?: string | null;
		voe_count_past_year?: number | null;
		hospitalization_count?: number | null;
		current_therapies: string[];
		failed_therapies: string[];
		hemoglobin?: number | null;
		hemoglobin_f_percentage?: number | null;
		age?: number | null;
	}
	export interface PAPayerRequirements {
		required_documentation: string[];
		step_therapy?: string[] | null;
		clinical_criteria: string[];
	}
	export interface Resume {
		name?: string | null;
		email?: string | null;
		experience: string[];
		skills: string[];
	}
	export interface Tool {
		type?: types.ToolType | null;
		name?: string | null;
		description?: string | null;
	}
	export interface ToolCall {
		tool?: types.ToolType | null;
		arguments?: string | null;
		reasoning?: string | null;
	}
}
