/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, Image } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
	? { [P in keyof T]?: RecursivePartialNull<T[P]> }
	: T | null;

export interface Checked<T, CheckName extends string = string> {
	value: T;
	checks: Record<CheckName, Check>;
}

export interface Check {
	name: string;
	expr: string;
	status: "succeeded" | "failed";
}

export function all_succeeded<CheckName extends string>(
	checks: Record<CheckName, Check>,
): boolean {
	return get_checks(checks).every((check) => check.status === "succeeded");
}

export function get_checks<CheckName extends string>(
	checks: Record<CheckName, Check>,
): Check[] {
	return Object.values(checks);
}
export enum ToolType {
	E2B_CODE_INTERPRETER = "E2B_CODE_INTERPRETER",
	PUBMED_SEARCH = "PUBMED_SEARCH",
	PERPLEXITY_SEARCH = "PERPLEXITY_SEARCH",
	EXA_SEARCH = "EXA_SEARCH",
}

export interface ChatResponseWithTools {
	message: string;
	requires_tools: boolean;
	tool_calls: ToolCall[];
	citations: Citation[];
}

export interface Citation {
	title: string;
	authors: string[];
	journal: string;
	year: number;
	pmid?: string | null;
	doi?: string | null;
	relevance_score: number;
}

export interface E2BCodeRequest {
	code: string;
	description: string;
	packages: string[];
	expected_output: string;
}

export interface MedicalChatResponse {
	message: string;
	requires_tools: boolean;
	tool_calls: ToolCall[];
	medical_context?: MedicalContext | null;
	suggestions: string[];
}

export interface MedicalContext {
	condition?: string | null;
	severity?: string | null;
	treatment_options: string[];
	key_considerations: string[];
	requires_literature: boolean;
}

export interface MedicalInsight {
	summary: string;
	key_findings: string[];
	citations: Citation[];
	recommendations: string[];
	confidence_level: string;
}

export interface PAAppealStrategy {
	denial_root_cause: string;
	documentation_gaps: string[];
	additional_evidence_needed: string[];
	appeal_strategy: string;
	recommend_peer_to_peer: boolean;
	peer_to_peer_talking_points?: string[] | null;
	timeline_recommendation: string;
	success_likelihood: string;
}

export interface PADrugInfo {
	drug_name: string;
	generic_name: string;
	indication: string;
	mechanism: string;
}

export interface PAExtractionResult {
	genotype?: string | null;
	voe_count_past_year?: number | null;
	hospitalization_count?: number | null;
	current_therapies: string[];
	failed_therapies: string[];
	hemoglobin?: number | null;
	hemoglobin_f_percentage?: number | null;
	extraction_notes: string[];
}

export interface PAJustificationResult {
	justification: string;
	citations: Citation[];
	confidence_level: string;
	key_points: string[];
	warnings: string[];
}

export interface PAPatientData {
	genotype?: string | null;
	voe_count_past_year: number;
	hospitalization_count: number;
	current_therapies: string[];
	failed_therapies: string[];
	hemoglobin?: number | null;
	hemoglobin_f_percentage?: number | null;
	age?: number | null;
}

export interface PAPayerRequirements {
	required_documentation: string[];
	step_therapy?: string[] | null;
	clinical_criteria: string[];
}

export interface Resume {
	name: string;
	email: string;
	experience: string[];
	skills: string[];
}

export interface Tool {
	type: ToolType;
	name: string;
	description: string;
}

export interface ToolCall {
	tool: ToolType;
	arguments: string;
	reasoning: string;
}
