/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { FieldType } from '@boundaryml/baml/native'
import {
	type ClassBuilder,
	type ClassViewer,
	type EnumBuilder,
	type EnumViewer,
	TypeBuilder as _TypeBuilder,
} from "@boundaryml/baml/type_builder";
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals";

export default class TypeBuilder {
	private tb: _TypeBuilder;

	ChatResponseWithTools: ClassViewer<
		"ChatResponseWithTools",
		"message" | "requires_tools" | "tool_calls" | "citations"
	>;

	Citation: ClassViewer<
		"Citation",
		| "title"
		| "authors"
		| "journal"
		| "year"
		| "pmid"
		| "doi"
		| "relevance_score"
	>;

	E2BCodeRequest: ClassViewer<
		"E2BCodeRequest",
		"code" | "description" | "packages" | "expected_output"
	>;

	MedicalChatResponse: ClassViewer<
		"MedicalChatResponse",
		| "message"
		| "requires_tools"
		| "tool_calls"
		| "medical_context"
		| "suggestions"
	>;

	MedicalContext: ClassViewer<
		"MedicalContext",
		| "condition"
		| "severity"
		| "treatment_options"
		| "key_considerations"
		| "requires_literature"
	>;

	MedicalInsight: ClassViewer<
		"MedicalInsight",
		| "summary"
		| "key_findings"
		| "citations"
		| "recommendations"
		| "confidence_level"
	>;

	PAAppealStrategy: ClassViewer<
		"PAAppealStrategy",
		| "denial_root_cause"
		| "documentation_gaps"
		| "additional_evidence_needed"
		| "appeal_strategy"
		| "recommend_peer_to_peer"
		| "peer_to_peer_talking_points"
		| "timeline_recommendation"
		| "success_likelihood"
	>;

	PADrugInfo: ClassViewer<
		"PADrugInfo",
		"drug_name" | "generic_name" | "indication" | "mechanism"
	>;

	PAExtractionResult: ClassViewer<
		"PAExtractionResult",
		| "genotype"
		| "voe_count_past_year"
		| "hospitalization_count"
		| "current_therapies"
		| "failed_therapies"
		| "hemoglobin"
		| "hemoglobin_f_percentage"
		| "extraction_notes"
	>;

	PAJustificationResult: ClassViewer<
		"PAJustificationResult",
		| "justification"
		| "citations"
		| "confidence_level"
		| "key_points"
		| "warnings"
	>;

	PAPatientData: ClassViewer<
		"PAPatientData",
		| "genotype"
		| "voe_count_past_year"
		| "hospitalization_count"
		| "current_therapies"
		| "failed_therapies"
		| "hemoglobin"
		| "hemoglobin_f_percentage"
		| "age"
	>;

	PAPayerRequirements: ClassViewer<
		"PAPayerRequirements",
		"required_documentation" | "step_therapy" | "clinical_criteria"
	>;

	Resume: ClassViewer<"Resume", "name" | "email" | "experience" | "skills">;

	Tool: ClassViewer<"Tool", "type" | "name" | "description">;

	ToolCall: ClassViewer<"ToolCall", "tool" | "arguments" | "reasoning">;

	ToolType: EnumViewer<
		"ToolType",
		| "E2B_CODE_INTERPRETER"
		| "PUBMED_SEARCH"
		| "PERPLEXITY_SEARCH"
		| "EXA_SEARCH"
	>;

	constructor() {
		this.tb = new _TypeBuilder({
			classes: new Set([
				"ChatResponseWithTools",
				"Citation",
				"E2BCodeRequest",
				"MedicalChatResponse",
				"MedicalContext",
				"MedicalInsight",
				"PAAppealStrategy",
				"PADrugInfo",
				"PAExtractionResult",
				"PAJustificationResult",
				"PAPatientData",
				"PAPayerRequirements",
				"Resume",
				"Tool",
				"ToolCall",
			]),
			enums: new Set(["ToolType"]),
			runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
		});

		this.ChatResponseWithTools = this.tb.classViewer("ChatResponseWithTools", [
			"message",
			"requires_tools",
			"tool_calls",
			"citations",
		]);

		this.Citation = this.tb.classViewer("Citation", [
			"title",
			"authors",
			"journal",
			"year",
			"pmid",
			"doi",
			"relevance_score",
		]);

		this.E2BCodeRequest = this.tb.classViewer("E2BCodeRequest", [
			"code",
			"description",
			"packages",
			"expected_output",
		]);

		this.MedicalChatResponse = this.tb.classViewer("MedicalChatResponse", [
			"message",
			"requires_tools",
			"tool_calls",
			"medical_context",
			"suggestions",
		]);

		this.MedicalContext = this.tb.classViewer("MedicalContext", [
			"condition",
			"severity",
			"treatment_options",
			"key_considerations",
			"requires_literature",
		]);

		this.MedicalInsight = this.tb.classViewer("MedicalInsight", [
			"summary",
			"key_findings",
			"citations",
			"recommendations",
			"confidence_level",
		]);

		this.PAAppealStrategy = this.tb.classViewer("PAAppealStrategy", [
			"denial_root_cause",
			"documentation_gaps",
			"additional_evidence_needed",
			"appeal_strategy",
			"recommend_peer_to_peer",
			"peer_to_peer_talking_points",
			"timeline_recommendation",
			"success_likelihood",
		]);

		this.PADrugInfo = this.tb.classViewer("PADrugInfo", [
			"drug_name",
			"generic_name",
			"indication",
			"mechanism",
		]);

		this.PAExtractionResult = this.tb.classViewer("PAExtractionResult", [
			"genotype",
			"voe_count_past_year",
			"hospitalization_count",
			"current_therapies",
			"failed_therapies",
			"hemoglobin",
			"hemoglobin_f_percentage",
			"extraction_notes",
		]);

		this.PAJustificationResult = this.tb.classViewer("PAJustificationResult", [
			"justification",
			"citations",
			"confidence_level",
			"key_points",
			"warnings",
		]);

		this.PAPatientData = this.tb.classViewer("PAPatientData", [
			"genotype",
			"voe_count_past_year",
			"hospitalization_count",
			"current_therapies",
			"failed_therapies",
			"hemoglobin",
			"hemoglobin_f_percentage",
			"age",
		]);

		this.PAPayerRequirements = this.tb.classViewer("PAPayerRequirements", [
			"required_documentation",
			"step_therapy",
			"clinical_criteria",
		]);

		this.Resume = this.tb.classViewer("Resume", [
			"name",
			"email",
			"experience",
			"skills",
		]);

		this.Tool = this.tb.classViewer("Tool", ["type", "name", "description"]);

		this.ToolCall = this.tb.classViewer("ToolCall", [
			"tool",
			"arguments",
			"reasoning",
		]);

		this.ToolType = this.tb.enumViewer("ToolType", [
			"E2B_CODE_INTERPRETER",
			"PUBMED_SEARCH",
			"PERPLEXITY_SEARCH",
			"EXA_SEARCH",
		]);
	}

	__tb() {
		return this.tb._tb();
	}

	string(): FieldType {
		return this.tb.string();
	}

	literalString(value: string): FieldType {
		return this.tb.literalString(value);
	}

	literalInt(value: number): FieldType {
		return this.tb.literalInt(value);
	}

	literalBool(value: boolean): FieldType {
		return this.tb.literalBool(value);
	}

	int(): FieldType {
		return this.tb.int();
	}

	float(): FieldType {
		return this.tb.float();
	}

	bool(): FieldType {
		return this.tb.bool();
	}

	list(type: FieldType): FieldType {
		return this.tb.list(type);
	}

	null(): FieldType {
		return this.tb.null();
	}

	map(key: FieldType, value: FieldType): FieldType {
		return this.tb.map(key, value);
	}

	union(types: FieldType[]): FieldType {
		return this.tb.union(types);
	}

	addClass<Name extends string>(name: Name): ClassBuilder<Name> {
		return this.tb.addClass(name);
	}

	addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
		return this.tb.addEnum(name);
	}

	addBaml(baml: string): void {
		this.tb.addBaml(baml);
	}
}
